### ISSUE TITLE
Memory leak when closing channels

### ISSUE THREAD

**Issue by nvx** [streadway/amqp#264]
This might be related to #149, although this issue occurs with autoAck disabled and Nack'ing messages, while 149 mentions autoAck being enabled.

Steps to reproduce:

1. Create a queue in RabbitMQ with ~50 messages in it, make each message a kb or so large to demonstrate it easier
2. Open a new connection
3. Open a new channel
4. Set Qos on channel to 50 prefetchCount, 0 prefetchSize, global false
5. Create a consumer with auto ack false
6. Consume a single message
7. Nack the message with multiple false, requeue true
8. Optionally Cancel the consumer (if this is done or not doesn't seem to change anything)
9. Close the channel
10. Loop from step 3

Each time this loops, it leaks a non-trivial amount of memory (up to a gig in few minutes):

```
(pprof) top
412.77MB of 420.27MB total (98.21%)
Dropped 109 nodes (cum <= 2.10MB)
      flat  flat%   sum%        cum   cum%
  412.77MB 98.21% 98.21%   413.77MB 98.45%  github.com/streadway/amqp.(*Channel).recvContent
         0     0% 98.21%   413.77MB 98.45%  github.com/streadway/amqp.(*Connection).demux
         0     0% 98.21%   413.77MB 98.45%  github.com/streadway/amqp.(*Connection).dispatchN
         0     0% 98.21%   418.27MB 99.52%  github.com/streadway/amqp.(*Connection).reader
         0     0% 98.21%     4.50MB  1.07%  github.com/streadway/amqp.(*reader).ReadFrame
         0     0% 98.21%     3.50MB  0.83%  github.com/streadway/amqp.(*reader).parseHeaderFrame
         0     0% 98.21%     3.50MB  0.83%  github.com/streadway/amqp.readTable
         0     0% 98.21%   419.77MB 99.88%  runtime.goexit
```

**Comment by michaelklishin** [comment]
@nvx can this be the same that's supposedly addressed by https://github.com/streadway/amqp/pull/250?

**Comment by michaelklishin** [comment]
@nvx also, if you cut steps 4 through 8th, does the behavior change?

**Comment by nvx** [comment]
I don't think #250 fixes this, because I did a go get of this package just before opening this issue and the issue still persisted (it looks like that PR was merged a couple of months ago), and the PR mentions channel.open failing causing the issue. In this instance channel.open is not failing (nothing is in fact).

I just tried cutting steps 4-8 and memory usage does not grow by a noticeable amount (2.4MB total memory usage after a quick test cutting those steps, vs hundreds of MBs growth in the same time with steps 4-8 enabled). Ditto if I only cut steps 5-8.

I cut steps 6-8 and the issue reappeared, growing by ~20MB each loop (which is about the same size as the the prefetch count * average message body size), so it looks like the consuming of a message and Nacking it is irrelevant.

**Comment by nvx** [comment]
For reference, this is against master on commit afe8eee29a74d213b1f3fb2586058157c397da60

**Comment by nvx** [comment]
Also important, if the queue has no messages in it to be consumed, the issue does not occur, so it definitely seems related to unacked messages not being cleaned up when the channel is closed rather than the channel itself causing a leak.

The more messages being prefetched, and the larger the message bodies of said messages, the more memory leaks.

**Comment by michaelklishin** [comment]
@nvx ok, thanks, the prefetch observation definitely helps narrow the issue down.

**Comment by nvx** [comment]
Were you able to reproduce this?

**Comment by michaelklishin** [comment]
We didn't have a chance to try. Maybe in a couple of weeks.

**Comment by nvx** [comment]
I recently ran into this again, so I've spent a bit of time tracking it down.

When a consumer is cancelled (either via Channel.Cancel(), or from closing the channel), the bufferDeliveries() goroutine in consumers.go leaks (execution is hung on the innermost select).

When the "in" channel is closed, it stops consuming from it by setting the channel to nil, but then attempts to drain the queue. The problem is that when a consumer is cancelled, you're unlikely to be interested in consuming the messages on the consumer channel anymore.

If after cancelling the consumer you drain the channel returned from ch.Consume() until the channel is empty, the memory leak goes away.

Alternatively, changing bufferDeliveries() if open else statement from "queueIn = nil" to simply "return", and converting the close(out) at the end of the function to defer close(out) at the start of the function, the issue would be fixed without needing to explicitly drain the channel until closed.

I'm not sure if the latter has any other implications though, and for cleanliness probably worth removing the queueIn variable at that point too.

**Comment by nvx** [comment]
I've made an example app that leaks really fast with a toggle for draining the channel which prevents the leak: https://pastebin.com/CDhBzXEw

It also has a flag for closing the connection each time too. Note the queueName specified will be deleted if it exists first (as to not end up with a tonne of messages in rabbit), then the queue is created and 50x 1kb messages published to it.

It will dump all goroutines every 1000 loops. If drainChannel is false, you can see the bufferDeliveries() goroutines pretty easily.

**Comment by michaelklishin** [comment]
@nvx thank you very much, that's very helpful!

**Comment by streadway** [comment]
Looks like an accurate assessment.

https://github.com/streadway/amqp/blob/master/consumers.go#L47-L57 could include a default case to drop the popped delivery when queueIn is closed.

**Comment by streadway** [comment]
@nvx can you explain a bit more why you wish to only consume one message from the deliveries channel that could have up to 50 messages in flight?

I am under the assumption that applications will want to see every message in-flight and receiving deliveries is concurrent with RPCs like Cancel and Close.

@michaelklishin what happens in rabbitmq to when a basic.ack is received after a basic.cancel? Do all messages in-flight get nack'd after basic.cancel or channel.close?

**Comment by nvx** [comment]
In my particular case it's not just cancelling the consumer, or even closing the channel, but also closing the connection so it is definitely not possible to ACK the messages at that point so the application doesn't even try after shutting it down.

**Comment by michaelklishin** [comment]
@streadway in-flight (unacknowledged) messages are requeued when the channel they were delivered on is closed. `basic.cancel` doesn't result in requeueing, there simply won't be any more deliveries.

**Comment by streadway** [comment]
@michaelklishin I assume that basic.ack on a a closed channel will then raise a connection exception.

This is starting to look like a lot like an API design flaw where deliveries are treated concurrent to other messages. It is a lot to ask for applications to know these cancel/close/ack semantics.

When autoAck is true, the application would likely drain/see all messages concurrently to close because they have ll been acknowledged.

When autoAck is false, the desired behavior is less clear. Should the app be able to see all inflight messages even if they are unack-able?

**Comment by streadway** [comment]
I propose:

We update the docs to describe that if every message is desired to be consumed, issue a `Channel.Cancel`, receive until the `<-chan Delivery` returned from `Channel.Consume` is closed, then call `Channel.Close` or `Connection.Close`.

Then change the behavior to when `Close` is called, all in-flight deliveries will be dropped.

**Comment by michaelklishin** [comment]
@streadway most clients immediately throw an exception if you attempt to do something on an already closed channel. Note that channel error notifications are asynchronous.

With [automatic acknowledgements](http://www.rabbitmq.com/confirms.html) all deliveries are "fired and forgotten", so they can be lost/unobserved by consumers in a bunch of other scenarios.
If that's not desired, that mode should not be used.

With manual acknowledgements, anything that's not acknowledged will be requeued. In other clients if you cancel a consumer, it will get all "in flight" messages dispatched. I haven't seen a lot of confusion around that. Those clients do not pass messages to consumers via a [Go] channel, though, so it's not necessarily a very fair comparison.

@streadway does the above answer your question? I'm not 100% I understand the concern. I think an explicitly closed channel can discard its unprocessed deliveries because with manual acks
they will be requeued and with auto mode the user has opted in for disabling all "safety protocols" anyway.

In Java and .NET clients, all outstanding consumer operations on a closing channel will be dispatched. I've seen opinions that claim that this is desired and not desired. It is a safer and more predictable way of doing things if you ask me.

**Comment by michaelklishin** [comment]
@streadway your proposal sounds reasonable.

**Comment by michaelklishin** [comment]
Giving it some more thought, I think the difference between this client and, say, .NET lies in the fact that in .NET the internal queue of unprocessed consumer operations is drained by the client automatically on channel closure. In this client, at least message deliveries are expected to be drained by the application.

So I think a more defensive approach would be reasonable, even if other mature clients do things differently.

**Comment by michaelklishin** [comment]
@nvx we believe #290/master address this. Can you please help us verify? Thank you.

**Comment by romanr321** [comment]
Still having this issue today with my Erlang Client. When my application crashes and restarts it re-opens the connection. I have a prefetchCount = 100, but after a relatively short time I have 20000 unacked messages in this channel. It shouldn't be possible but it is. If I turn the application off they get released, but if it crashes they don't, I'm guessing it restarts so fast that RabbitMQ can't tell the connection went down, but the counter of how many messages it has gets messed up.

**Comment by lukebakken** [comment]
@romanr321 - you say "Erlang Client" but `streadway/amqp` is a golang client library.

> guessing it restarts so fast that RabbitMQ can't tell the connection went down

I'm sure RabbitMQ detects there is a new connection and something else is in play. If you could provide code that reproduces what you report we could look into it.
